version: "3"

services:

  redis:
    restart: always
    image: redis:7.2.3-alpine
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379

  postgres:
    restart: always
    image: postgres:14-alpine
    container_name: pgsqldb
    hostname: pgsqldb
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./apps/dbmigration/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=s3cr3t123
      - POSTGRES_USER=wildangbudhi
      - POSTGRES_DB=analyticsdb
    # user: "502:20"
  
  metabase:
    restart: always
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    ports:
      - 3000:3000
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=wildangbudhi
      - MB_DB_PASS=s3cr3t123
      - MB_DB_HOST=pgsqldb
  
  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379/0', '--port=5555']
    ports:
      - 5555:5555
    depends_on:
      - redis
  
  scheduler:
    restart: always
    build:
      context: ./apps/scheduler
      dockerfile: Dockerfile
    container_name: scheduler
    hostname: scheduler
    environment:
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/1
    depends_on:
      - redis
      - postgres

  worker1:
    restart: always
    build:
      context: ./apps/worker
      dockerfile: Dockerfile
    container_name: worker1
    hostname: worker1
    environment:
      - DB_CONN_STRING=postgresql://wildangbudhi:s3cr3t123@pgsqldb:5432/analyticsdb
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/1
    depends_on:
      - redis
      - postgres